heat_template_version: 2015-04-30

description: Sets up a wordpress server

parameter_groups:
  - label: Other
    description: Other parameters
    parameters:
    - title
    - admin-user
    - admin-password
    - admin-email
    - flavor
    - image
    - key
    - volume_name
    - volume_size
    - private_network
    - public_network

parameters:
  title:
    type: string
    label: Wordpress site name
    description: Name of the Wordpress site
    default: "CC User Wordpress site"
  admin-user:
    type: string
    label: Admin username
    description: The account name of the wordpress site administrator.
  admin-password:
    type: string
    label: Admin password
    description: The password for the administrator account.
    hidden: true
    constraints:
      - length: {min: 16, max: 32 }
        description: Password length must be between 16 and 32 characters.
      - allowed_pattern: '[a-zA-Z0-9]+'
        description: Password must contain only letters, numbers.
  admin-email:
    type: string
    label: Admin email
    description: Email for site administrator
    constraints:
      - allowed_pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        description: Must be a valid email
  flavor:
    type: string
    label: Flavor
    description: Hardware flavor to be used for the server,  it is best to select a flavor starting with a "p" for persistent
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    label: Image
    description: Base image to use to install wordpress on, it is best to select "Ubuntu-16.04.2-Xenial-x64-2017-07" others may work but haven't been tested.
    constraints:
      - custom_constraint: glance.image
  key:
    type: string
    label: Key-pair name
    description: Name of a previously generated key-pair in OpenStack to be used when connecting to the server via ssh. Usefull for performing maintance tasks.
    constraints:
      - custom_constraint: nova.keypair
  volume_name:
    type: string
    label: Volume Name
    default: wordpress_root
    description: Name of the volume to boot from. A new volume will be created.
  volume_size:
    type: number
    label: Volume Size
    default: 20
    description: Size of the volume in GB
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    constraints:
      - custom_constraint: neutron.network
  public_network:
    type: string
    description: Network to use for obtaining public IP (VLAN3337 for west-cloud, net04_ext for east-cloud)
    label: Public Network
    default: net04_ext
    constraints:
      - allowed_values:
        - VLAN3337
        - net04_ext
resources:
  wordpress-server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      key_name: {get_param: key}
      name: wordpress-server
      block_device_mapping: [{device_name: "vda", volume_id: {get_resource: wordpress_volume}, delete_on_termination: "false"}]
      networks:
        - port: {get_resource: wordpress_port}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            package_update: true
            package_upgrade: true
            packages:
              - apache2
              - mysql-server
              - php
              - php-dev
              - libapache2-mod-php
              - php-mcrypt
              - php-mysql
              - php-curl
              - php-gd
              - php-mbstring
              - php-xml
              - php-xmlrpc
              - libssh2-1-dev
              - php-fpm
              - fail2ban
            write_files:
              - content: |
                  #!/bin/bash
                  
                  WP_ADMIN_USER=ADMINUSER
                  WP_ADMIN_PASSWD=ADMINUSERPASS
                  WP_ADMIN_EMAIL=ADMINUSEREMAIL
                  WP_TITLE=SITETITLE
                  
                  
                  #use this version of ssh2 for php, the 
                  #php-ssh2 package doesn't seem to work, there is a known bug with it.
                  pecl install ssh2-1.1.2
                  
                  #add extension to php.ini
                  echo "addeding php-ssh2 extension to php.ini ..."
                  echo "extension=ssh2.so">>/etc/php/7.0/apache2/php.ini
                  
                  echo "making DB_PASSWORD ..."
                  DB_PASSWORD=$(tr -dc _A-Za-z0-9 < /dev/urandom | head -c16) # Generate a random password
                  DB_NAME="wordpress"
                  DB_USER="wordpress"
                  DB_HOST=localhost
                  
                  echo "getting latest wordpress ..."
                  TMP_DIR=/tmp
                  wget http://wordpress.org/latest.tar.gz -O $TMP_DIR/latest.tar.gz
                  echo "untarring wordpress ..."
                  tar xzf $TMP_DIR/latest.tar.gz -C $TMP_DIR
                  
                  # create the database, and configure the wordpress user.
                  echo "configuring database ..."
                  mysql <<EOF
                  CREATE DATABASE $DB_NAME;
                  GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
                  ON $DB_NAME.*
                  TO $DB_USER@$DB_HOST
                  IDENTIFIED BY '$DB_PASSWORD';
                  FLUSH PRIVILEGES;
                  EOF
                  
                  # copy the config file and then configure database name, username, and password
                  echo "editing the wordpress configuration ..."
                  cp $TMP_DIR/wordpress/wp-config-sample.php $TMP_DIR/wordpress/wp-config.php
                  sed -i "s/database_name_here/$DB_NAME/g" $TMP_DIR/wordpress/wp-config.php
                  sed -i "s/password_here/$DB_PASSWORD/g" $TMP_DIR/wordpress/wp-config.php
                  sed -i "s/username_here/$DB_USER/g" $TMP_DIR/wordpress/wp-config.php
                  
                  # configure security keys : https://codex.wordpress.org/Editing_wp-config.php#Security_Keys
                  echo "configuring wordpress security keys ..."
                  for i in $(seq 1 8)
                  do
                    key=$(tr -dc _A-Za-z0-9 < /dev/urandom | head -c64)
                    sed -i "0,/put your unique phrase here/s/put your unique phrase here/$key/" $TMP_DIR/wordpress/wp-config.php
                  done
                  
                  #create a user to manage (update/install plugins) for wordpress
                  echo "creating user, wp-user, to manage updating/installing plugins for wordpress ..."
                  adduser --disabled-password wp-user << EOF
                  wp-user
                  
                  
                  
                  Y
                  EOF
                  
                  #add wp-user to www-data group
                  adduser wp-user www-data
                  
                  #
                  ##setup ssh keys for wp-user
                  echo "setting up wp-user ssh keys ..."
                  su - wp-user -c "ssh-keygen -t rsa -b 4096 << EOF
                  /home/wp-user/wp_rsa
                  
                  EOF"
                  
                  chown wp-user:www-data /home/wp-user/wp_rsa*
                  chmod 0640 /home/wp-user/wp_rsa*
                  mkdir /home/wp-user/.ssh
                  chown wp-user:wp-user /home/wp-user/.ssh/
                  chmod 0700 /home/wp-user/.ssh/
                  echo "from=127.0.0.1">/home/wp-user/.ssh/authorized_keys
                  cat /home/wp-user/wp_rsa.pub >>/home/wp-user/.ssh/authorized_keys
                  chown wp-user:wp-user /home/wp-user/.ssh/authorized_keys
                  chmod 0644 /home/wp-user/.ssh/authorized_keys
                  
                  #configure wp to use ssh for updates and plugin installation
                  echo "configuring wordpress to use ssh for updates and installs ..."
                  echo "define('FTP_PUBKEY','/home/wp-user/wp_rsa.pub');">>$TMP_DIR/wordpress/wp-config.php
                  echo "define('FTP_PRIKEY','/home/wp-user/wp_rsa');">>$TMP_DIR/wordpress/wp-config.php
                  echo "define('FTP_USER','wp-user');">>$TMP_DIR/wordpress/wp-config.php
                  echo "define('FTP_PASS','');">>$TMP_DIR/wordpress/wp-config.php
                  echo "define('FTP_HOST','127.0.0.1:22');">>$TMP_DIR/wordpress/wp-config.php
                  #echo "define('FS_METHOD', 'direct');">>$TMP_DIR/wordpress/wp-config.php
                  
                  echo "moving install from $TMP_DIR/wordpress/ to /var/www/html/ ..."
                  rm /var/www/html/index.html
                  mv $TMP_DIR/wordpress/* /var/www/html/
                  
                  #make wp-user owner of wp-site
                  echo "setting permissions on files/directories in /var/www/html ..."
                  chown -R wp-user:www-data /var/www/html
                  chmod u=rwX,g=rX,o=rX -R /var/www/html
                  find /var/www/html -type d -exec echo chmod u+s,g+s {} \;
                  chmod o-rx /var/www/html/wp-config.php
                  
                  #install wp-cli
                  echo "installing wp-cli ..."
                  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                  chmod +x wp-cli.phar
                  mv wp-cli.phar /usr/local/bin/wp
                  
                  sudo systemctl restart apache2
                  
                  #do initial setup of wordpress
                  echo "performing initial setup of wordpress site ..."
                  su - wp-user -c "cd /var/www/html;wp core install --url=https://$(curl http://icanhazptr.com/) --title='$WP_TITLE' --admin_user='$WP_ADMIN_USER' --admin_password='$WP_ADMIN_PASSWD' --admin_email='$WP_ADMIN_EMAIL'"
                  
                  #install plugin to log wordpress authentication attempts
                  su - wp-user -c "cd /var/www/html; wp plugin install wp-fail2ban; wp plugin activate wp-fail2ban"
                  
                  #install fail2ban wordpress filters
                  cp /var/www/html/wp-content/plugins/wp-fail2ban/filters.d/wordpress-hard.conf /etc/fail2ban/filter.d/
                  cp /var/www/html/wp-content/plugins/wp-fail2ban/filters.d/wordpress-soft.conf /etc/fail2ban/filter.d/
                  echo "[wordpress-hard]">/etc/fail2ban/jail.d/wordpress.conf
                  echo "enabled = true">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "filter = wordpress-hard">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "logpath = /var/log/auth.log">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "maxretry = 1">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "port = http,https">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "[wordpress-soft]">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "enabled = true">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "filter = wordpress-soft">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "logpath = /var/log/auth.log">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "maxretry = 3">>/etc/fail2ban/jail.d/wordpress.conf
                  echo "port = http,https">>/etc/fail2ban/jail.d/wordpress.conf
                  
                  #disable use of xmlrpc multicall function to amplify brute force attempts
                  #this causes problems with wp cli, so must be done after all the wp cli stuff is done
                  echo "add_filter('xmlrpc_enabled', '__return_false');">>$TMP_DIR/wordpress/wp-config.php
                  
                  sudo systemctl restart apache2
                  
                path: /tmp/bootstrap-wp.sh
                permissions: "0755"
              - content: |
                  #!/bin/bash
                  wc_notify --data-binary '{"status": "SUCCESS", "reason": "mediawiki server CI done"}'
                path: /tmp/finished.sh
                permissions: "0755"
            runcmd:
              - echo -n "127.0.1.1 ">>/etc/hosts
              - cat /etc/hostname>>/etc/hosts
              - ["cd","/tmp"]
              - ["git","clone","https://github.com/cgeroux/heat-wordpress.git"]
              - ["/tmp/heat-wordpress/self-signed-ssl-setup.py","SERVERADDRESS"]
              - bash /tmp/bootstrap-wp.sh
              - bash /tmp/finished.sh
          params:
            TITLE: {get_param: title}
            ADMINUSER: {get_param: admin-user}
            ADMINUSERPASS: {get_param: admin-password}
            SERVERADDRESS: { get_attr: [ wordpress_floating_ip, floating_ip_address ] }
            ADMINUSEREMAIL: {get_param: admin-email}
            SITETITLE: {get_param: title}
            wc_notify: {get_attr: ['wordpress_wait_handle','curl_cli']}
  wordpress_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: private_network}
      security_groups: [{get_resource: wordpress_security},default]
  wordpress_security:
    type: OS::Neutron::SecurityGroup
    properties:
      name: wordpress_security
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
  wordpress_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      port_id: {get_resource: wordpress_port}
      floating_network: {get_param: public_network}
  wordpress_wait_handle:
    type: OS::Heat::WaitConditionHandle
  wordpress_wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: wordpress_wait_handle}
      count: 1
      timeout: 1200
  wordpress_volume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: volume_size}
      image: {get_param: image}
      name: {get_param: volume_name}
outputs:
  Admin_acct_info:
    description: 
    value: " "
  public_ip:
    description: Floating IP address of server, can be used to ssh into server
    value: { get_attr: [ wordpress_floating_ip, floating_ip_address ] }
  wordpress-url:
    description: Link to wordpress site
    value:
      str_replace:
        template: http://<hostip>
        params:
          <hostip>: { get_attr: [ wordpress_floating_ip, floating_ip_address ] }

